"""empty message

Revision ID: e7fd0c762fd1
Revises: 685e37925de5
Create Date: 2026-02-12 10:37:29.223187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fd0c762fd1'
down_revision = '685e37925de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tar_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tar_type', sa.String(length=20), nullable=False),
    sa.Column('as_on_date', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tar_archive')
    # ### end Alembic commands ###
